In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from re import T
a=[1,2,3,4,11,13,12,10,5,6,7,8,9]
serise_a=pd.Series(a)
print(type(serise_a),"\n",serise_a.sort_values(ascending=True))

<class 'pandas.core.series.Series'>
 0      1
1      2
2      3
3      4
8      5
9      6
10     7
11     8
12     9
7     10
4     11
6     12
5     13
dtype: int64

In [ ]:
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}
energy_df=pd.DataFrame(data=data)
print(energy_df)

  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

In [ ]:
# Impute missing values in 'Energy Consumption (MWh)' with the mean

energy_df.iloc[:, 1] = energy_df["Energy Consumption (MWh)"].fillna(energy_df["Energy Consumption (MWh)"].mean())

# Impute missing values in 'Cost (Million $)' with the mean

energy_df.iloc[:, 2] = energy_df["Cost (Million $)"].fillna(energy_df["Cost (Million $)"].mean())

print("\nData After Imputing Missing Values with Mean:")

print(energy_df)

Data After Imputing Missing Values with Mean:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

In [ ]:
import pandas as pd
import numpy as np
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving CO2_Emissions_1960-2018.csv to CO2_Emissions_1960-2018.csv

In [ ]:
df = pd.read_csv("CO2_Emissions_1960-2018.csv")
df.head()

,Country Name,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Aruba,204.631696,208.837879,226.081890,214.785217,207.626699,185.213644,172.158729,210.819017,194.917536,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,0.906060,0.922474,0.930816,0.940570,0.996033,1.047280,1.033908,1.052204,1.079727,...,1.021954,1.048876,1.005338,1.021646,1.031833,1.041145,0.987393,0.971016,0.959978,0.933541
2,Afghanistan,0.046057,0.053589,0.073721,0.074161,0.086174,0.101285,0.107399,0.123409,0.115142,...,0.211306,0.297065,0.407074,0.335351,0.263716,0.234037,0.232176,0.208857,0.203328,0.200151
3,Africa Western and Central,0.090880,0.095283,0.096612,0.112376,0.133258,0.184803,0.193676,0.189305,0.143989,...,0.426770,0.472819,0.497023,0.490867,0.504655,0.507671,0.480743,0.472959,0.476438,0.515544
4,Angola,0.100835,0.082204,0.210533,0.202739,0.213562,0.205891,0.268937,0.172096,0.289702,...,1.205902,1.221515,1.216317,1.204799,1.261542,1.285365,1.260921,1.227703,1.034317,0.887380

In [ ]:
print(df.shape)
print(df.columns)
print(df.info())
df.describe()

(266, 60)
Index(['Country Name', '1960', '1961', '1962', '1963', '1964', '1965', '1966',
       '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975',
       '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984',
       '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993',
       '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002',
       '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', '2017', '2018'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 60 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  266 non-null    object
 1   1960          203 non-null    float64
 2   1961          204 non-null    float64
 3   1962          206 non-null    float64
 4   1963          207 non-null    float64
 5   1964          213 non-null    float64
 6   1965          213 non-null    float64
 7   1966          213 non-null    float64
 8   1967          213 non-null    float64
 9   1968          213 non-null    float64
 10  1969          213 non-null    float64
 11  1970          214 non-null    float64
 12  1971          215 non-null    float64
 13  1972          216 non-null    float64
 14  1973          216 non-null    float64
 15  1974          216 non-null    float64
 16  1975          216 non-null    float64
 17  1976          216 non-null    float64
 18  1977          216 non-null    float64
 19  1978          216 non-null    float64
 20  1979          216 non-null    float64
 21  1980          216 non-null    float64
 22  1981          216 non-null    float64
 23  1982          216 non-null    float64
 24  1983          216 non-null    float64
 25  1984          216 non-null    float64
 26  1985          216 non-null    float64
 27  1986          216 non-null    float64
 28  1987          216 non-null    float64
 29  1988          216 non-null    float64
 30  1989          216 non-null    float64
 31  1990          238 non-null    float64
 32  1991          239 non-null    float64
 33  1992          238 non-null    float64
 34  1993          238 non-null    float64
 35  1994          238 non-null    float64
 36  1995          239 non-null    float64
 37  1996          239 non-null    float64
 38  1997          239 non-null    float64
 39  1998          239 non-null    float64
 40  1999          239 non-null    float64
 41  2000          239 non-null    float64
 42  2001          239 non-null    float64
 43  2002          239 non-null    float64
 44  2003          239 non-null    float64
 45  2004          239 non-null    float64
 46  2005          239 non-null    float64
 47  2006          239 non-null    float64
 48  2007          239 non-null    float64
 49  2008          239 non-null    float64
 50  2009          239 non-null    float64
 51  2010          239 non-null    float64
 52  2011          239 non-null    float64
 53  2012          239 non-null    float64
 54  2013          239 non-null    float64
 55  2014          239 non-null    float64
 56  2015          239 non-null    float64
 57  2016          239 non-null    float64
 58  2017          239 non-null    float64
 59  2018          239 non-null    float64
dtypes: float64(59), object(1)
memory usage: 124.8+ KB
None

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
count,203.000000,204.000000,206.000000,207.000000,213.000000,213.000000,213.000000,213.000000,213.000000,213.000000,...,239.000000,239.000000,239.000000,239.000000,239.000000,239.000000,239.000000,239.000000,239.000000,239.000000
mean,3.160220,3.292338,3.462051,3.906006,4.007034,4.029132,3.992162,4.249468,4.363587,5.240497,...,4.494702,4.329083,4.315602,4.372246,4.280935,4.195690,4.148874,4.147100,4.154185,4.158613
std,14.821169,15.114669,16.286958,16.909771,16.325047,15.139695,14.054838,15.943855,14.936638,19.691750,...,5.177846,5.006608,4.912689,4.894707,4.844110,4.732984,4.654801,4.592901,4.575980,4.547079
min,0.007984,0.007857,0.008435,0.009336,0.011589,0.011851,0.013248,0.011791,-0.020098,0.016104,...,0.000000,0.000000,0.000000,0.035207,0.042976,0.039617,0.037904,0.026146,0.028010,0.026169
25%,0.195031,0.185078,0.211355,0.208805,0.219304,0.236942,0.258556,0.265284,0.293462,0.334922,...,0.736515,0.779051,0.798791,0.805751,0.815681,0.824377,0.806683,0.818367,0.851900,0.827804
50%,0.616754,0.662374,0.659399,0.706050,0.793962,0.794770,0.885508,1.032198,1.004645,1.104632,...,2.741639,2.667232,2.689378,2.869867,2.695691,2.698682,2.696240,2.754968,2.667119,2.691814
75%,2.060142,2.420962,2.526705,2.270349,2.523331,2.630170,3.202366,3.913345,4.072719,4.167117,...,6.524149,6.110808,6.188510,6.315302,6.284435,6.108660,5.920151,5.836392,6.158644,6.069018
max,204.631696,208.837879,226.081890,214.785217,207.626699,185.213644,172.158729,210.819017,194.917536,253.544574,...,34.544976,33.544700,32.305726,33.373132,31.927018,32.693532,32.470570,32.128042,32.179371,32.415639

In [ ]:
df.isnull().sum()

Country Name     0
1960            63
1961            62
1962            60
1963            59
1964            53
1965            53
1966            53
1967            53
1968            53
1969            53
1970            52
1971            51
1972            50
1973            50
1974            50
1975            50
1976            50
1977            50
1978            50
1979            50
1980            50
1981            50
1982            50
1983            50
1984            50
1985            50
1986            50
1987            50
1988            50
1989            50
1990            28
1991            27
1992            28
1993            28
1994            28
1995            27
1996            27
1997            27
1998            27
1999            27
2000            27
2001            27
2002            27
2003            27
2004            27
2005            27
2006            27
2007            27
2008            27
2009            27
2010            27
2011            27
2012            27
2013            27
2014            27
2015            27
2016            27
2017            27
2018            27
dtype: int64

In [ ]:
numeric_columns = df.select_dtypes(include=np.number).columns
df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].mean())

text_columns = df.select_dtypes(include="object").columns
df[text_columns] = df[text_columns].fillna("Unknown")

df.isnull().sum()

Country Name    0
1960            0
1961            0
1962            0
1963            0
1964            0
1965            0
1966            0
1967            0
1968            0
1969            0
1970            0
1971            0
1972            0
1973            0
1974            0
1975            0
1976            0
1977            0
1978            0
1979            0
1980            0
1981            0
1982            0
1983            0
1984            0
1985            0
1986            0
1987            0
1988            0
1989            0
1990            0
1991            0
1992            0
1993            0
1994            0
1995            0
1996            0
1997            0
1998            0
1999            0
2000            0
2001            0
2002            0
2003            0
2004            0
2005            0
2006            0
2007            0
2008            0
2009            0
2010            0
2011            0
2012            0
2013            0
2014            0
2015            0
2016            0
2017            0
2018            0
dtype: int64

In [ ]:
df.corr(numeric_only=True)

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
1960,1.000000,0.998917,0.997261,0.916596,0.917775,0.901076,0.904022,0.942557,0.933719,0.901359,...,0.159382,0.173761,0.171592,0.165246,0.163683,0.158571,0.156652,0.154875,0.153218,0.154005
1961,0.998917,1.000000,0.998660,0.916295,0.918984,0.903620,0.905789,0.942656,0.933383,0.901109,...,0.171242,0.185594,0.183675,0.177291,0.176453,0.171571,0.169996,0.168071,0.166055,0.166571
1962,0.997261,0.998660,1.000000,0.917753,0.921385,0.908230,0.909591,0.943545,0.932635,0.901336,...,0.174823,0.187633,0.185968,0.179810,0.178629,0.173179,0.172046,0.170041,0.167871,0.168142
1963,0.916596,0.916295,0.917753,1.000000,0.996411,0.984613,0.984459,0.992776,0.988365,0.918710,...,0.314849,0.328769,0.323388,0.323054,0.316274,0.318681,0.319502,0.318859,0.317617,0.320225
1964,0.917775,0.918984,0.921385,0.996411,1.000000,0.995077,0.994550,0.993308,0.987736,0.916547,...,0.338562,0.352452,0.347172,0.345680,0.338693,0.339608,0.340628,0.339523,0.337791,0.339849
1965,0.901076,0.903620,0.908230,0.984613,0.995077,1.000000,0.999095,0.982886,0.976086,0.901449,...,0.373903,0.388244,0.382885,0.380493,0.372560,0.371635,0.373172,0.371933,0.369571,0.371329
1966,0.904022,0.905789,0.909591,0.984459,0.994550,0.999095,1.000000,0.985051,0.980107,0.904179,...,0.378238,0.392471,0.386751,0.384202,0.375733,0.374734,0.375900,0.375118,0.372917,0.375108
1967,0.942557,0.942656,0.943545,0.992776,0.993308,0.982886,0.985051,1.000000,0.997712,0.938809,...,0.320687,0.329587,0.323781,0.324642,0.318017,0.319120,0.319398,0.318484,0.317702,0.319705
1968,0.933719,0.933383,0.932635,0.988365,0.987736,0.976086,0.980107,0.997712,1.000000,0.939844,...,0.341581,0.348479,0.341193,0.343449,0.335797,0.337650,0.337359,0.336316,0.335913,0.338314
1969,0.901359,0.901109,0.901336,0.918710,0.916547,0.901449,0.904179,0.938809,0.939844,1.000000,...,0.328409,0.332743,0.326594,0.330767,0.329565,0.332018,0.337657,0.340267,0.343344,0.340394
1970,0.931821,0.931329,0.930731,0.934963,0.931744,0.913063,0.916524,0.953419,0.951576,0.968356,...,0.321816,0.328593,0.324687,0.326411,0.325019,0.326648,0.323175,0.326387,0.329340,0.330502
1971,0.897204,0.897622,0.897351,0.924189,0.922551,0.907114,0.909810,0.941678,0.941245,0.971303,...,0.383186,0.379417,0.376747,0.382583,0.380023,0.381205,0.378907,0.382160,0.385240,0.385899
1972,0.883442,0.883907,0.883849,0.922447,0.919881,0.904424,0.907086,0.936037,0.935820,0.958575,...,0.406307,0.404238,0.401888,0.406928,0.403863,0.405468,0.401725,0.405394,0.408424,0.409937
1973,0.886423,0.887094,0.885871,0.920227,0.916436,0.897942,0.900542,0.934998,0.935177,0.959735,...,0.391593,0.388059,0.386075,0.391947,0.389594,0.391716,0.388395,0.391382,0.393997,0.394932
1974,0.901378,0.902238,0.899951,0.918116,0.914930,0.895691,0.899146,0.937383,0.938388,0.962367,...,0.383456,0.380384,0.379147,0.384022,0.382012,0.383202,0.380214,0.382819,0.385210,0.385960
1975,0.850827,0.852774,0.850144,0.897973,0.895956,0.880469,0.884875,0.916087,0.921421,0.942148,...,0.466441,0.456219,0.455548,0.463826,0.459914,0.461673,0.458509,0.461001,0.463457,0.465036
1976,0.956695,0.956690,0.955559,0.930142,0.923110,0.896811,0.898915,0.951862,0.947283,0.960183,...,0.247097,0.248533,0.247583,0.250207,0.249841,0.250757,0.250053,0.250388,0.251586,0.251294
1977,0.886998,0.889831,0.887652,0.901591,0.899507,0.881611,0.885318,0.925588,0.928437,0.946172,...,0.420002,0.411497,0.411300,0.418590,0.416773,0.417362,0.414625,0.415138,0.416774,0.417403
1978,0.854832,0.856890,0.855147,0.883396,0.882225,0.867247,0.872016,0.904329,0.908864,0.932085,...,0.473799,0.474698,0.473447,0.477936,0.476370,0.478092,0.473145,0.474559,0.477030,0.478183
1979,0.869521,0.871416,0.868934,0.922243,0.918361,0.900891,0.905179,0.936757,0.942174,0.933657,...,0.462692,0.465865,0.463491,0.468359,0.465453,0.468453,0.464580,0.464507,0.466047,0.467863
1980,0.892042,0.894524,0.892689,0.922295,0.921103,0.905120,0.909063,0.942172,0.944883,0.936852,...,0.436474,0.438891,0.437468,0.441882,0.439888,0.441240,0.437715,0.437827,0.438951,0.440338
1981,0.914943,0.918081,0.915971,0.939786,0.937634,0.920556,0.924173,0.958574,0.960953,0.955545,...,0.398124,0.419784,0.416259,0.415360,0.416717,0.420292,0.422384,0.421199,0.421449,0.420305
1982,0.934839,0.937946,0.935723,0.935949,0.932212,0.911521,0.915158,0.957568,0.958568,0.954465,...,0.351318,0.370311,0.367649,0.366487,0.368019,0.371328,0.372378,0.371202,0.371787,0.370814
1983,0.824243,0.829418,0.826012,0.865082,0.868131,0.859583,0.865986,0.887732,0.896608,0.898515,...,0.531773,0.565543,0.562045,0.558234,0.561454,0.565679,0.566390,0.565656,0.567144,0.566221
1984,0.960075,0.962108,0.960600,0.930813,0.926497,0.903908,0.906866,0.954841,0.951820,0.955505,...,0.277922,0.295872,0.294004,0.291730,0.293828,0.295596,0.296991,0.296442,0.297138,0.295874
1985,0.966952,0.968654,0.967259,0.925133,0.920068,0.895678,0.898602,0.950290,0.946091,0.949298,...,0.245010,0.261290,0.259733,0.257393,0.259439,0.260821,0.261643,0.261100,0.261675,0.260576
1986,0.169089,0.180754,0.176599,0.305645,0.328452,0.358644,0.367815,0.320898,0.347654,0.375674,...,0.782021,0.832234,0.825840,0.819275,0.824713,0.830854,0.833731,0.832027,0.833215,0.829699
1987,0.219378,0.230576,0.225424,0.324365,0.346549,0.373061,0.383865,0.346444,0.372645,0.403584,...,0.775241,0.824871,0.819021,0.810954,0.817089,0.822148,0.822464,0.821303,0.823086,0.820402
1988,0.247881,0.259160,0.253243,0.345234,0.366030,0.390828,0.402575,0.367955,0.394080,0.416857,...,0.779559,0.825970,0.821384,0.814409,0.819702,0.825023,0.821159,0.821933,0.824385,0.823861
1989,0.248745,0.259453,0.253952,0.360166,0.380567,0.405334,0.416560,0.379966,0.405979,0.429309,...,0.790370,0.833372,0.828908,0.822916,0.826417,0.831589,0.827872,0.829990,0.833051,0.833389
1990,0.181778,0.188155,0.183420,0.284669,0.302905,0.326579,0.334747,0.298104,0.323486,0.357442,...,0.818502,0.875278,0.868338,0.858573,0.868037,0.860819,0.854510,0.853174,0.854441,0.848659
1991,0.185786,0.192139,0.188688,0.307519,0.327017,0.354060,0.361311,0.316801,0.341457,0.375697,...,0.838673,0.892474,0.884749,0.876361,0.883728,0.876361,0.872328,0.871022,0.871290,0.865227
1992,0.166494,0.174308,0.165496,0.287947,0.297584,0.310803,0.319913,0.297302,0.327546,0.360002,...,0.843327,0.886102,0.880362,0.875080,0.882265,0.878342,0.873686,0.876667,0.877996,0.875248
1993,0.165381,0.173376,0.164365,0.294193,0.303465,0.316135,0.324829,0.300841,0.331188,0.361166,...,0.848959,0.895470,0.888397,0.882193,0.888433,0.886746,0.882059,0.883332,0.884231,0.881519
1994,0.158288,0.166287,0.157965,0.293940,0.302405,0.314601,0.323229,0.299970,0.330273,0.364783,...,0.855960,0.901666,0.892794,0.887662,0.894490,0.894811,0.891102,0.892123,0.892990,0.889742
1995,0.172216,0.183782,0.182763,0.324320,0.345740,0.376330,0.381781,0.329895,0.352367,0.383134,...,0.902875,0.946096,0.937515,0.932404,0.937768,0.936971,0.937096,0.938577,0.938105,0.933370
1996,0.170910,0.182057,0.180648,0.325243,0.345533,0.374819,0.380840,0.329929,0.353073,0.380285,...,0.901644,0.946604,0.936355,0.930253,0.935841,0.935394,0.935252,0.936296,0.935559,0.930905
1997,0.166031,0.176800,0.175553,0.329472,0.348319,0.376755,0.382539,0.331498,0.354308,0.382482,...,0.904558,0.947616,0.937493,0.932323,0.937288,0.938600,0.938912,0.940116,0.939998,0.935962
1998,0.164914,0.176704,0.176404,0.336729,0.356848,0.386977,0.391614,0.337805,0.359665,0.383223,...,0.911073,0.948002,0.937810,0.934539,0.938524,0.940030,0.942336,0.942780,0.941957,0.937130
1999,0.165120,0.176457,0.176383,0.348114,0.367582,0.398037,0.402327,0.345648,0.367283,0.384346,...,0.914848,0.951491,0.941414,0.939012,0.941218,0.943981,0.946593,0.946388,0.945218,0.940915
2000,0.171989,0.183546,0.183366,0.339735,0.360895,0.392952,0.397455,0.340084,0.361366,0.374114,...,0.920567,0.959498,0.950157,0.946254,0.948497,0.950246,0.952471,0.952317,0.951020,0.947221
2001,0.171070,0.182539,0.182716,0.342303,0.363449,0.395971,0.400147,0.341677,0.362808,0.381385,...,0.923163,0.960766,0.951108,0.947705,0.948811,0.950474,0.953010,0.952584,0.951322,0.947422
2002,0.169321,0.180407,0.180807,0.359189,0.379447,0.411784,0.415364,0.354081,0.375482,0.383555,...,0.928927,0.964386,0.955067,0.952701,0.952021,0.953576,0.955715,0.954662,0.953266,0.950011
2003,0.171458,0.182159,0.182642,0.355972,0.376818,0.409737,0.413956,0.351752,0.373002,0.379461,...,0.933774,0.970930,0.961731,0.958201,0.957342,0.957341,0.957697,0.956893,0.955491,0.952739
2004,0.176794,0.187082,0.187600,0.358855,0.380833,0.415129,0.419102,0.354405,0.375363,0.377423,...,0.934736,0.973937,0.965219,0.961083,0.959259,0.958103,0.958448,0.957026,0.955834,0.953672
2005,0.174053,0.185417,0.186802,0.374858,0.397205,0.432518,0.435075,0.365768,0.385714,0.374798,...,0.933532,0.974844,0.966943,0.963328,0.961505,0.961674,0.962188,0.959274,0.958066,0.956584
2006,0.174116,0.185808,0.187727,0.360177,0.382804,0.418273,0.421585,0.353142,0.372250,0.356683,...,0.945815,0.987236,0.981064,0.976612,0.974181,0.972671,0.970146,0.967170,0.965303,0.965236
2007,0.172752,0.184028,0.185695,0.353812,0.375588,0.410167,0.414013,0.347791,0.367019,0.348612,...,0.948527,0.991965,0.987517,0.982709,0.981444,0.980075,0.977350,0.974800,0.972881,0.972650
2008,0.173149,0.184573,0.186410,0.342665,0.365478,0.400675,0.404509,0.339777,0.358683,0.347568,...,0.953211,0.995147,0.991518,0.987826,0.986593,0.983349,0.980607,0.977782,0.975932,0.974975
2009,0.159382,0.171242,0.174823,0.314849,0.338562,0.373903,0.378238,0.320687,0.341581,0.328409,...,1.000000,0.952342,0.952197,0.969280,0.947824,0.942677,0.938653,0.935536,0.931744,0.933323
2010,0.173761,0.185594,0.187633,0.328769,0.352452,0.388244,0.392471,0.329587,0.348479,0.332743,...,0.952342,1.000000,0.997286,0.992879,0.993446,0.989749,0.985993,0.982360,0.979704,0.979004
2011,0.171592,0.183675,0.185968,0.323388,0.347172,0.382885,0.386751,0.323781,0.341193,0.326594,...,0.952197,0.997286,1.000000,0.995690,0.995806,0.991283,0.988258,0.985112,0.982393,0.981913
2012,0.165246,0.177291,0.179810,0.323054,0.345680,0.380493,0.384202,0.324642,0.343449,0.330767,...,0.969280,0.992879,0.995690,1.000000,0.995439,0.992249,0.989014,0.985306,0.982497,0.982319
2013,0.163683,0.176453,0.178629,0.316274,0.338693,0.372560,0.375733,0.318017,0.335797,0.329565,...,0.947824,0.993446,0.995806,0.995439,1.000000,0.997190,0.994003,0.991076,0.988860,0.987900
2014,0.158571,0.171571,0.173179,0.318681,0.339608,0.371635,0.374734,0.319120,0.337650,0.332018,...,0.942677,0.989749,0.991283,0.992249,0.997190,1.000000,0.997545,0.994376,0.992430,0.991629
2015,0.156652,0.169996,0.172046,0.319502,0.340628,0.373172,0.375900,0.319398,0.337359,0.337657,...,0.938653,0.985993,0.988258,0.989014,0.994003,0.997545,1.000000,0.997528,0.995486,0.993471
2016,0.154875,0.168071,0.170041,0.318859,0.339523,0.371933,0.375118,0.318484,0.336316,0.340267,...,0.935536,0.982360,0.985112,0.985306,0.991076,0.994376,0.997528,1.000000,0.998986,0.997648
2017,0.153218,0.166055,0.167871,0.317617,0.337791,0.369571,0.372917,0.317702,0.335913,0.343344,...,0.931744,0.979704,0.982393,0.982497,0.988860,0.992430,0.995486,0.998986,1.000000,0.998895
2018,0.154005,0.166571,0.168142,0.320225,0.339849,0.371329,0.375108,0.319705,0.338314,0.340394,...,0.933323,0.979004,0.981913,0.982319,0.987900,0.991629,0.993471,0.997648,0.998895,1.000000