<a href="https://colab.research.google.com/github/joypatel07/Internship/blob/main/day4_09_07_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from re import T
a=[1,2,3,4,11,13,12,10,5,6,7,8,9]
serise_a=pd.Series(a)
print(type(serise_a),"\n",serise_a.sort_values(ascending=True))

<class 'pandas.core.series.Series'>
 0      1
1      2
2      3
3      4
8      5
9      6
10     7
11     8
12     9
7     10
4     11
6     12
5     13
dtype: int64

In [3]:
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}
energy_df=pd.DataFrame(data=data)
print(energy_df)

  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

In [4]:
energy_df.isnull().sum()

Energy Source               0
Energy Consumption (MWh)    2
Cost (Million $)            2
dtype: int64

In [5]:
# Remove rows with any missing values

cleaned_df = energy_df.dropna()

subset_df  = energy_df.dropna(subset = "Energy Consumption (MWh)")
print("\nData After Removing Rows with Missing Values:")
print(cleaned_df)

print(subset_df)

print(energy_df)

Data After Removing Rows with Missing Values:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
4       Biomass                    2500.0             250.0
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
2    Hydropower                    2900.0               NaN
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

In [6]:
energy_df.iloc[:, 1] = energy_df["Energy Consumption (MWh)"].fillna(energy_df["Energy Consumption (MWh)"].mean())

# Impute missing values in 'Cost (Million $)' with the mean

energy_df.iloc[:, 2] = energy_df["Cost (Million $)"].fillna(energy_df["Cost (Million $)"].mean())

print("\nData After Imputing Missing Values with Mean:")

print(energy_df)

Data After Imputing Missing Values with Mean:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

In [7]:
forward_filled_df = energy_df.ffill()

# energy_df = energy_df.ffill()

print("before forward filling")

print(energy_df)


# print(forward_filled_df.columns)

print("\nData After Forward Filling:")

print(forward_filled_df)

before forward filling
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

Data After Forward Filling:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

In [8]:
energy_df1 = energy_df.copy()
energy_df1

  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

In [1]:
import pandas as pd
import numpy as np

# Create DataFrame
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}

energy_df = pd.DataFrame(data)

# Create copies
energy_df_mean = energy_df.copy()
energy_df_ffill = energy_df.copy()
energy_df_bfill = energy_df.copy()

# ---------------- Mean Imputation ----------------
energy_df_mean["Energy Consumption (MWh)"] = energy_df_mean["Energy Consumption (MWh)"].fillna(
    energy_df_mean["Energy Consumption (MWh)"].mean()
)

energy_df_mean["Cost (Million $)"] = energy_df_mean["Cost (Million $)"].fillna(
    energy_df_mean["Cost (Million $)"].mean()
)

print("Data After Mean Imputation:")
print(energy_df_mean)

# ---------------- Forward Fill ----------------
print("\nBefore Forward Fill:")
print(energy_df_ffill)

forward_filled_df = energy_df_ffill.ffill()

print("\nData After Forward Fill:")
print(forward_filled_df)

# ---------------- Backward Fill ----------------
print("\nBefore Backward Fill:")
print(energy_df_bfill)

backward_filled_df = energy_df_bfill.bfill()

print("\nData After Backward Fill:")
print(backward_filled_df)

Data After Mean Imputation:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

Before Forward Fill:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

Data After Forward Fill:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    1200.0             400.0
2    Hydropower                    2900.0             400.0
3    Geothermal                    2900.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

Before Backward Fill:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

Data After Backward Fill:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2900.0             400.0
2    Hydropower                    2900.0             150.0
3    Geothermal                    2500.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

In [4]:
# Green Skilling & Sustainability Dataset Analysis
import pandas as pd
df = pd.read_csv("GreenSkilling_Sustainability_Dataset.csv")

In [5]:
print("First 5 Rows")
print(df.head())

First 5 Rows
   ID    Country  Solar_Energy_%  Wind_Energy_%  Green_Skilling_Training  \
0   1  Australia            63.0             10                   2221.0
1   2      Kenya            71.0             50                   4879.0
2   3        USA            89.0             37                   4462.0
3   4      Japan            70.0             76                    924.0
4   5     Brazil             NaN             66                   3726.0

   Green_Jobs  CO2_Emissions_tonnes_per_capita  Recycling_Rate_%
0        8426                              139                36
1        3628                              121                60
2        9911                              286                63
3        5846                              158                73
4        8591                              237                73

In [6]:
print("\nDataset Shape")
print(df.shape)

Dataset Shape
(30, 8)

In [7]:
print("\nColumn Names")
print(df.columns)

Column Names
Index(['ID', 'Country', 'Solar_Energy_%', 'Wind_Energy_%',
       'Green_Skilling_Training', 'Green_Jobs',
       'CO2_Emissions_tonnes_per_capita', 'Recycling_Rate_%'],
      dtype='object')

In [8]:
print("\nDataset Information")
print(df.info())

Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ID                               30 non-null     int64
 1   Country                          30 non-null     object
 2   Solar_Energy_%                   28 non-null     float64
 3   Wind_Energy_%                    30 non-null     int64
 4   Green_Skilling_Training          28 non-null     float64
 5   Green_Jobs                       30 non-null     int64
 6   CO2_Emissions_tonnes_per_capita  30 non-null     int64
 7   Recycling_Rate_%                 30 non-null     int64
dtypes: float64(2), int64(5), object(1)
memory usage: 2.0+ KB
None

In [9]:
print("\nStatistical Summary")
print(df.describe())

Statistical Summary
              ID  Solar_Energy_%  Wind_Energy_%  Green_Skilling_Training  \
count  30.000000       28.000000      30.000000                28.000000
mean   15.500000       48.642857      42.500000              2296.785714
std     8.803408       24.493709      23.069236              1648.907660
min     1.000000       12.000000       8.000000               100.000000
25%     8.250000       21.750000      24.000000               883.250000
50%    15.500000       52.000000      40.000000              1904.000000
75%    22.750000       67.000000      61.000000              3795.250000
max    30.000000       89.000000      80.000000              4879.000000

        Green_Jobs  CO2_Emissions_tonnes_per_capita  Recycling_Rate_%
count    30.000000                        30.000000         30.000000
mean   5406.233333                       210.600000         45.666667
std    3292.277565                       102.818085         18.283841
min      74.000000                        36.000000         13.000000
25%    3182.500000                       122.000000         31.500000
50%    4816.500000                       240.000000         49.500000
75%    8353.500000                       298.000000         60.000000
max    9970.000000                       382.000000         74.000000

In [11]:
print("\nNull Values")
print(df.isnull().sum())

Null Values
ID                                 0
Country                            0
Solar_Energy_%                     2
Wind_Energy_%                      0
Green_Skilling_Training            2
Green_Jobs                         0
CO2_Emissions_tonnes_per_capita    0
Recycling_Rate_%                   0
dtype: int64

In [12]:
# Numerical columns are filled with their mean values.

df["Solar_Energy_%"] = df["Solar_Energy_%"].fillna(df["Solar_Energy_%"].mean())

df["Green_Skilling_Training"] = df["Green_Skilling_Training"].fillna(
    df["Green_Skilling_Training"].mean()
)

print("\nNull Values After Handling")
print(df.isnull().sum())

Null Values After Handling
ID                                 0
Country                            0
Solar_Energy_%                     0
Wind_Energy_%                      0
Green_Skilling_Training            0
Green_Jobs                         0
CO2_Emissions_tonnes_per_capita    0
Recycling_Rate_%                   0
dtype: int64

In [13]:
# Correlation

print("\nCorrelation Matrix")
print(df.corr(numeric_only=True))

Correlation Matrix
                                       ID  Solar_Energy_%  Wind_Energy_%  \
ID                               1.000000       -0.015532      -0.228625
Solar_Energy_%                  -0.015532        1.000000       0.147656
Wind_Energy_%                   -0.228625        0.147656       1.000000
Green_Skilling_Training         -0.320742        0.159504      -0.015474
Green_Jobs                      -0.206112        0.085949       0.042859
CO2_Emissions_tonnes_per_capita -0.013715       -0.124558      -0.050054
Recycling_Rate_%                -0.204377        0.743196       0.750407

                                 Green_Skilling_Training  Green_Jobs  \
ID                                             -0.320742   -0.206112
Solar_Energy_%                                  0.159504    0.085949
Wind_Energy_%                                  -0.015474    0.042859
Green_Skilling_Training                         1.000000    0.093963
Green_Jobs                                      0.093963    1.000000
CO2_Emissions_tonnes_per_capita                 0.151487    0.032360
Recycling_Rate_%                                0.116042    0.098940

                                 CO2_Emissions_tonnes_per_capita  \
ID                                                     -0.013715
Solar_Energy_%                                         -0.124558
Wind_Energy_%                                          -0.050054
Green_Skilling_Training                                 0.151487
Green_Jobs                                              0.032360
CO2_Emissions_tonnes_per_capita                         1.000000
Recycling_Rate_%                                       -0.100225

                                 Recycling_Rate_%
ID                                      -0.204377
Solar_Energy_%                           0.743196
Wind_Energy_%                            0.750407
Green_Skilling_Training                  0.116042
Green_Jobs                               0.098940
CO2_Emissions_tonnes_per_capita         -0.100225
Recycling_Rate_%                         1.000000

In [14]:
print("Average Solar Energy")
print(df["Solar_Energy_%"].mean())

Average Solar Energy
48.64285714285714

In [15]:
print("\nAverage Wind Energy")
print(df["Wind_Energy_%"].mean())

Average Wind Energy
42.5

In [16]:
print("\nAverage CO2 Emissions")
print(df["CO2_Emissions_tonnes_per_capita"].mean())

Average CO2 Emissions
210.6

In [17]:
print("\nAverage Recycling Rate")
print(df["Recycling_Rate_%"].mean())

Average Recycling Rate
45.666666666666664

In [18]:
print("\nCountry Wise Average Green Jobs")
print(df.groupby("Country")["Green_Jobs"].mean())

Country Wise Average Green Jobs
Country
Australia    8426.000000
Brazil       7789.500000
Canada       3316.000000
France       4926.666667
Germany      6460.000000
India        3369.333333
Japan        7862.000000
Kenya        2894.666667
UAE          4983.800000
USA          5125.000000
Name: Green_Jobs, dtype: float64

In [19]:
print("\nCountry Wise Average Solar Energy")
print(df.groupby("Country")["Solar_Energy_%"].mean())

Country Wise Average Solar Energy
Country
Australia    63.000000
Brazil       36.571429
Canada       15.000000
France       57.666667
Germany      14.000000
India        43.666667
Japan        59.333333
Kenya        49.333333
UAE          47.600000
USA          58.833333
Name: Solar_Energy_%, dtype: float64