<a href="https://colab.research.google.com/github/joypatel07/Internship/blob/main/day4_09_07_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from re import T
a=[1,2,3,4,11,13,12,10,5,6,7,8,9]
serise_a=pd.Series(a)
print(type(serise_a),"\n",serise_a.sort_values(ascending=True))

<class 'pandas.core.series.Series'>
 0      1
1      2
2      3
3      4
8      5
9      6
10     7
11     8
12     9
7     10
4     11
6     12
5     13
dtype: int64

In [3]:
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}
energy_df=pd.DataFrame(data=data)
print(energy_df)

  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

In [4]:
energy_df.isnull().sum()

Energy Source               0
Energy Consumption (MWh)    2
Cost (Million $)            2
dtype: int64

In [5]:
# Remove rows with any missing values

cleaned_df = energy_df.dropna()

subset_df  = energy_df.dropna(subset = "Energy Consumption (MWh)")
print("\nData After Removing Rows with Missing Values:")
print(cleaned_df)

print(subset_df)

print(energy_df)

Data After Removing Rows with Missing Values:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
4       Biomass                    2500.0             250.0
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
2    Hydropower                    2900.0               NaN
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

In [6]:
energy_df.iloc[:, 1] = energy_df["Energy Consumption (MWh)"].fillna(energy_df["Energy Consumption (MWh)"].mean())

# Impute missing values in 'Cost (Million $)' with the mean

energy_df.iloc[:, 2] = energy_df["Cost (Million $)"].fillna(energy_df["Cost (Million $)"].mean())

print("\nData After Imputing Missing Values with Mean:")

print(energy_df)

Data After Imputing Missing Values with Mean:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

In [7]:
forward_filled_df = energy_df.ffill()

# energy_df = energy_df.ffill()

print("before forward filling")

print(energy_df)


# print(forward_filled_df.columns)

print("\nData After Forward Filling:")

print(forward_filled_df)

before forward filling
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

Data After Forward Filling:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

In [8]:
energy_df1 = energy_df.copy()
energy_df1

  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

In [9]:
import pandas as pd
import numpy as np

# Create DataFrame
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}

energy_df = pd.DataFrame(data)

# Create copies
energy_df_mean = energy_df.copy()
energy_df_ffill = energy_df.copy()
energy_df_bfill = energy_df.copy()

# ---------------- Mean Imputation ----------------
energy_df_mean["Energy Consumption (MWh)"] = energy_df_mean["Energy Consumption (MWh)"].fillna(
    energy_df_mean["Energy Consumption (MWh)"].mean()
)

energy_df_mean["Cost (Million $)"] = energy_df_mean["Cost (Million $)"].fillna(
    energy_df_mean["Cost (Million $)"].mean()
)

print("Data After Mean Imputation:")
print(energy_df_mean)

# ---------------- Forward Fill ----------------
print("\nBefore Forward Fill:")
print(energy_df_ffill)

forward_filled_df = energy_df_ffill.ffill()

print("\nData After Forward Fill:")
print(forward_filled_df)

# ---------------- Backward Fill ----------------
print("\nBefore Backward Fill:")
print(energy_df_bfill)

backward_filled_df = energy_df_bfill.bfill()

print("\nData After Backward Fill:")
print(backward_filled_df)

Data After Mean Imputation:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

Before Forward Fill:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

Data After Forward Fill:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    1200.0             400.0
2    Hydropower                    2900.0             400.0
3    Geothermal                    2900.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

Before Backward Fill:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

Data After Backward Fill:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2900.0             400.0
2    Hydropower                    2900.0             150.0
3    Geothermal                    2500.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN